version: "3.4"

# Development environment override
services:
  php:
    image: ghcr.io/kilip/yawik/php-dev
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
    environment:
      APP_ENV: dev
      MONGODB_URL: mongodb://yawik:yawik@database:27017

  pwa:
    image: ghcr.io/kilip/yawik/${FRONTEND:-nuxt}-dev
    build:
      context: "${FRONTEND:-nuxt}"
      target: "yawik_${FRONTEND:-nuxt}_dev"
    volumes:
      - "./${FRONTEND:-nuxt}:/usr/src/pwa:rw,cached"
  caddy:
    volumes:
      - ./api/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/public:/srv/api/public:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo /srv/mercure-assets/

  database:
    volumes:
      - ./var/mongo/data:/var/lib/mongodb/data:rw
      - ./docker/mongo:/dump:rw
