version: '3.4'
services:
  php:
    container_name: yawik.php
    image: ghcr.io/kilip/yawik-php
    build:
      context: ./
      target: yawik_php
      dockerfile: ./docker/php/Dockerfile
      args:
        UID: '${WWWUSER}'
        GID: '${WWWGROUP}'
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  pwa:
    container_name: yawik.pwa
    image: ghcr.io/kilip/yawik-pwa
    build:
      context: ./
      target: yawik_pwa_prod
      dockerfile: ./docker/pwa/Dockerfile
    environment:
      NEXT_PUBLIC_ENTRYPOINT: http://caddy
    ports:
      - "3000:3000"

  caddy:
    container_name: yawik.caddy
    image: ghcr.io/kilip/yawik-caddy
    build:
      context: ./
      target: yawik_caddy
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - php
      - pwa
    environment:
      PWA_UPSTREAM: pwa:3000
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY:-!ChangeMe!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeMe!}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - ./var/caddy/data:/data
      - ./var/caddy/config:/config
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp

  database:
    container_name: yawik.database
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=yawik
      - MONGO_INITDB_ROOT_USERNAME=yawik
      - MONGO_INITDB_ROOT_PASSWORD=yawik
    volumes:
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./var/mongo/data:/data/db
    ports:
      - "27017:27017"

volumes:
  php_socket: