version: "3.4"

services:
  php:
    container_name: yawik.php
    image: registry.gitlab.com/kilip/yawik/php
    build:
      context: ./api
      target: yawik_php
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  pwa:
    container_name: yawik.pwa
    image: registry.gitlab.com/kilip/yawik/pwa
    build:
      context: ./pwa
      target: yawik_pwa_prod
    environment:
      API_PLATFORM_CLIENT_GENERATOR_ENTRYPOINT: http://caddy
      NEXT_PUBLIC_ENTRYPOINT: http://caddy

  caddy:
    container_name: yawik.caddy
    image: registry.gitlab.com/kilip/yawik/caddy
    build:
      context: api/
      target: yawik_caddy
    depends_on:
      - php
      - pwa
    environment:
      PWA_UPSTREAM: pwa:3000
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY:-!ChangeMe!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeMe!}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp

  database:
    container_name: yawik.database
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=api
      - MONGO_INITDB_ROOT_USERNAME=api-platform
      - MONGO_INITDB_ROOT_PASSWORD=api-platform
    volumes:
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./var/mongo/data:/var/lib/mongodb/data:rw
    ports:
      - "27017:27017"

volumes:
  php_socket:
  caddy_data:
  caddy_config:
